//
//  ETDSWarning.h
//  Stripe3DS2
//
//  Created by Cameron Sabol on 2/12/19.
//  Copyright © 2019 Stripe. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/**
 The `ETDSWarningSeverity` enum defines the severity levels of warnings generated
 during SDK initialization. @see ETDSThreeDS2Service
 */
typedef NS_ENUM(NSInteger, ETDSWarningSeverity) {
    /**
     Low severity
     */
    ETDSWarningSeverityLow = 0,

    /**
     Medium severity
     */
    ETDSWarningSeverityMedium,

    /**
     High severity
     */
    ETDSWarningSeverityHigh,
};

/**
 The `ETDSWarning` class represents warnings generated by `ETDSThreeDS2Service` during
 security checks run during initialization. @see ETDSThreeDS2Service
 */
@interface ETDSWarning : NSObject

/**
 Designated initializer for `ETDSWarning`.
 */
- (instancetype)initWithIdentifier:(NSString *)identifier
                           message:(NSString *)message
                          severity:(ETDSWarningSeverity)severity NS_DESIGNATED_INITIALIZER;

/**
 `ETDSWarning` should not be directly initialized.
 */
- (instancetype)init NS_UNAVAILABLE;

/**
 The identifier for this warning instance.
 */
@property (nonatomic, readonly) NSString *identifier;

/**
 The descriptive message for this warning.
 */
@property (nonatomic, readonly) NSString *message;

/**
 The severity of this warning.
 */
@property (nonatomic, readonly) ETDSWarningSeverity severity;

@end

NS_ASSUME_NONNULL_END
